version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=production

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend