name: Backend CI

on:
  push:
    branches: [ main ]
    paths: 
      - 'backend/**'
      - 'docker-compose.yml'
      - '.github/workflows/backend-ci.yml'

env:
  DOCKERHUB_USER: ${{ secrets.DOCKERHUB_BOKOVM}}
  IMAGE_NAME: your-dockerhub-username/assistant-backend

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov

    - name: Run tests
      working-directory: ./backend
      env:
        DATABASE_URL: postgresql://test:test@postgres:5432/test
      run: |
        pytest --cov=app --cov-report=xml

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        push: true
        tags: ${{ env.DOCKERHUB_BOKOVM }}/assistant-backend:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Logout of Docker
      if: always()
      run: docker logout