name: Deploy

on:
  workflow_run:
    workflows: ["Backend CI", "Frontend CI"]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Deploy to server
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_BOKOVM }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker login -u ${{ secrets.DOCKERHUB_BOKOVM }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker-compose -f docker-compose.prod.yml pull
          docker-compose -f docker-compose.prod.yml up -d
          docker system prune -af